db_api:
    url: "http://192.168.0.37:3002/api"
    routes:
        detection: "/detections"
        audio: "/audio"
        station: "/stations"

flask_server:
    host: "0.0.0.0"
    port: 4000

paths:
    segments_dir: "data/segments"
    detections_dir: "data/detections"
    logs_dir: "data/logs"
    detections_log: "data/detections/detections.csv"

websocket_stream:
    url: "http://192.168.0.37:3002"

audio_capture:
    sample_rate: 48000
    channels: 1
    dtype: int16
    sample_width: 2

birdnet:
    model: "BirdNet-Analyser"
    version: "v2.4"
