station:
    id: "149cd7cd-350e-4a84-a3dd-f6d6b6afaf5f"
    api_key: "c069c1fb-aa87-4ac6-8359-15dafa25bb2d"
    station_name: "Development Station"
    location:
      lat: 54.607868
      lon: -5.926437
      desc: "Back garden, Belfast, Northern Ireland"

detection_config:
    min_confidence: 0.25
    high_confidence_threshold: 0.5
    segment_duration: 10
    segment_overlap: 0

species:
    ignore_list: []