paths:
    configs_dir: "config"
    segments_dir: "data/segments"
    recordings_dir: "data/recordings"
    detections_dir: "data/detections"
    logs_dir: "data/logs"
    detections_log: "data/detections/detections.csv"
    
audio_capture:
    sample_rate: 48000
    channels: 1
    dtype: int16
    audio_format: "wav"
    audio_device: None
    inactivity_timeout: 6

segmenter_config:
    segment_duration: 3
    segment_overlap: 2

allowable_states:
    - unannounced
    - announced
    - claimed
    - configured

birdnet:
    model: "BirdNet-Analyser"
    version: "v2.4"
    sensitivity: 1.5
    analyser_min_confidence: 0.1
