scripts:
    start_capture: "main.py"

temp:
    process: "/tmp/audiobirder_process.pid"

paths:
    configs_dir: "config"
    segments_dir: "data/segments"
    detections_dir: "data/detections"
    logs_dir: "data/logs"
    detections_log: "data/detections/detections.csv"
    
audio_capture:
    sample_rate: 48000
    channels: 1
    dtype: int16
    sample_width: 2

birdnet:
    model: "BirdNet-Analyser"
    version: "v2.4"
